### ISSUE TITLE
Template does not work on newest (0.12.0) release

### ISSUE THREAD

**Issue by PierreV23** [capy-ui/zig-template#11]
```
build_capy.zig:62:22: error: expected 2 arguments, found 3
        const self = @fieldParentPtr(WebServerStep, "step", step);
```

**Comment by zenith391** [comment]
Yea, that was expected because capy was still on version [`2024.3.0-mach`](https://machengine.org/about/nominated-zig/) but now that [`2024.5.0-mach`](https://machengine.org/about/nominated-zig/) is out I'll upgrade the code and it will also work on 0.12.0

**Comment by mhcerri** [comment]
Hi. It doesn't work with 0.13 either.

**Comment by zenith391** [comment]
Fixed by ecb4031, it now works on Zig 0.13.0
